import 'dart:convert';

import 'thai_canon_evidence_alignment_classification.dart';
import 'thai_canon_evidence_alignment_runner.dart';

/// Markdown / JSON report generator for alignment QA (internal only).
abstract final class ThaiCanonEvidenceAlignmentReport {
  static String toMarkdown(ThaiCanonEvidenceAlignmentAudit audit) {
    final buffer = StringBuffer()
      ..writeln('# Thai Canon Evidence Alignment QA Report')
      ..writeln()
      ..writeln('Generated by `ThaiCanonEvidenceAlignmentRunner` (deterministic).')
      ..writeln()
      ..writeln('## Coverage metrics')
      ..writeln()
      ..writeln('| Metric | Value |')
      ..writeln('|---|---|')
      ..writeln('| Fixtures audited | ${audit.fixtureResults.length} |')
      ..writeln('| Total report sections | ${audit.totalReportSections} |')
      ..writeln(
        '| Section rows with STRONG_MATCH evidence | '
        '${audit.sectionsWithStrongMatch} |',
      )
      ..writeln(
        '| Section rows with RELATED_BUT_WEAK evidence | '
        '${audit.sectionsWithWeakEvidence} |',
      )
      ..writeln(
        '| Section rows with no evidence | ${audit.sectionsWithNoEvidence} |',
      )
      ..writeln(
        '| Out of Canon scope signals | ${audit.totalOutOfCanonScopeSignals} |',
      )
      ..writeln(
        '| In-scope unmapped signals | ${audit.totalInCanonScopeUnmapped} |',
      )
      ..writeln(
        '| Trace-only evidence candidates | ${audit.totalTraceOnlyCandidates} |',
      )
      ..writeln(
        '| Skipped remedy count (aggregate) | '
        '${audit.totalSkippedRemedyCount} |',
      )
      ..writeln(
        '| Skipped Taksa count (aggregate) | ${audit.totalSkippedTaksaCount} |',
      )
      ..writeln(
        '| Skipped lookup table count (aggregate) | '
        '${audit.totalSkippedLookupTableCount} |',
      )
      ..writeln(
        '| Skipped periodStatus notes | '
        '${audit.totalSkippedPeriodStatusNotes} |',
      )
      ..writeln('| Canon unit ids used | ${audit.canonUnitIdsUsed.length} |')
      ..writeln()
      ..writeln('### Classification totals')
      ..writeln();
    for (final entry in audit.classificationCounts.entries) {
      if (entry.value == 0) continue;
      buffer.writeln('- ${entry.key.wire}: ${entry.value}');
    }
    buffer
      ..writeln()
      ..writeln('## Mapping split')
      ..writeln()
      ..writeln('### Out of Canon scope (not mapping failures)')
      ..writeln();
    for (final entry in audit.topOutOfCanonScopeKeys) {
      buffer.writeln('- `${entry.key}` (${entry.value} fixtures)');
    }
    buffer
      ..writeln()
      ..writeln('### True in-scope unmapped')
      ..writeln();
    for (final entry in audit.topInCanonScopeUnmappedKeys) {
      buffer.writeln('- `${entry.key}` (${entry.value} fixtures)');
    }
    buffer
      ..writeln()
      ..writeln('### Skipped by safety policy')
      ..writeln()
      ..writeln('- Remedies: ${audit.totalSkippedRemedyCount} unit-slots (aggregate)')
      ..writeln('- Lookup tables: ${audit.totalSkippedLookupTableCount} unit-slots (aggregate)')
      ..writeln()
      ..writeln('### Skipped due to missing runtime key')
      ..writeln()
      ..writeln('- Taksa: ${audit.totalSkippedTaksaCount} unit-slots (aggregate)')
      ..writeln('- periodStatus notes: ${audit.totalSkippedPeriodStatusNotes}')
      ..writeln()
      ..writeln('## Fixture summaries')
      ..writeln();
    for (final result in audit.fixtureResults) {
      buffer
        ..writeln('### ${result.fixture.id}')
        ..writeln()
        ..writeln('- Label: ${result.fixture.label}')
        ..writeln('- Birth: ${result.fixture.birthSummary}')
        ..writeln('- Lagna: ${result.lagnaKey} · Lord: ${result.lagnaLordKey}')
        ..writeln('- Mahabhuta keys: ${result.mahabhutaKeys.join(", ")}')
        ..writeln('- Attachments: ${result.attachmentCount}')
        ..writeln('- Evidence refs: ${result.evidenceRefCount}')
        ..writeln(
          '- Out of scope: ${result.bundle.trace.outOfCanonScopeSignals.length}',
        )
        ..writeln(
          '- In-scope unmapped: '
          '${result.bundle.trace.inCanonScopeUnmappedSignals.length}',
        )
        ..writeln(
          '- Trace-only: ${result.bundle.trace.traceOnlyEvidenceCandidates.length}',
        )
        ..writeln(
          '- Sections with evidence: '
          '${result.sectionsWithEvidence.join(", ")}',
        )
        ..writeln(
          '- Sections without evidence: '
          '${result.sectionsWithoutEvidence.join(", ")}',
        )
        ..writeln();
    }
    buffer
      ..writeln('## Top unused Canon domains (by unit count)')
      ..writeln();
    for (final entry in audit.topUnusedCanonDomains) {
      buffer.writeln('- ${entry.key}: ${entry.value} units');
    }
    buffer
      ..writeln()
      ..writeln('## False confidence risks')
      ..writeln();
    for (final risk in audit.falseConfidenceRisks) {
      buffer.writeln('- $risk');
    }
    buffer
      ..writeln()
      ..writeln('## Integration readiness')
      ..writeln();
    for (final entry in audit.integrationReadiness.entries) {
      buffer.writeln('- ${entry.key}: ${entry.value.wire}');
    }
    return buffer.toString();
  }

  static String toJson(ThaiCanonEvidenceAlignmentAudit audit) {
    return const JsonEncoder.withIndent('  ').convert({
      'fixtureCount': audit.fixtureResults.length,
      'classificationCounts': {
        for (final e in audit.classificationCounts.entries)
          if (e.value > 0) e.key.wire: e.value,
      },
      'coverage': {
        'totalReportSections': audit.totalReportSections,
        'sectionsWithStrongMatch': audit.sectionsWithStrongMatch,
        'sectionsWithWeakEvidence': audit.sectionsWithWeakEvidence,
        'sectionsWithNoEvidence': audit.sectionsWithNoEvidence,
        'totalOutOfCanonScopeSignals': audit.totalOutOfCanonScopeSignals,
        'totalInCanonScopeUnmapped': audit.totalInCanonScopeUnmapped,
        'totalTraceOnlyCandidates': audit.totalTraceOnlyCandidates,
        'totalUnmappedSignals': audit.totalUnmappedSignals,
        'totalSkippedRemedyCount': audit.totalSkippedRemedyCount,
        'totalSkippedTaksaCount': audit.totalSkippedTaksaCount,
        'totalSkippedLookupTableCount': audit.totalSkippedLookupTableCount,
        'totalSkippedPeriodStatusNotes': audit.totalSkippedPeriodStatusNotes,
      },
      'topOutOfCanonScopeKeys': [
        for (final e in audit.topOutOfCanonScopeKeys)
          {'key': e.key, 'fixtureHits': e.value},
      ],
      'topInCanonScopeUnmappedKeys': [
        for (final e in audit.topInCanonScopeUnmappedKeys)
          {'key': e.key, 'fixtureHits': e.value},
      ],
      'topUnusedCanonDomains': [
        for (final e in audit.topUnusedCanonDomains)
          {'domain': e.key, 'unitCount': e.value},
      ],
      'falseConfidenceRisks': audit.falseConfidenceRisks,
      'integrationReadiness': {
        for (final e in audit.integrationReadiness.entries)
          e.key: e.value.wire,
      },
      'fixtures': [
        for (final r in audit.fixtureResults)
          {
            'id': r.fixture.id,
            'birthSummary': r.fixture.birthSummary,
            'lagnaKey': r.lagnaKey,
            'lagnaLordKey': r.lagnaLordKey,
            'attachmentCount': r.attachmentCount,
            'evidenceRefCount': r.evidenceRefCount,
            'outOfCanonScopeCount': r.bundle.trace.outOfCanonScopeSignals.length,
            'inCanonScopeUnmappedCount':
                r.bundle.trace.inCanonScopeUnmappedSignals.length,
            'traceOnlyCount': r.bundle.trace.traceOnlyEvidenceCandidates.length,
            'sectionsWithEvidence': r.sectionsWithEvidence,
            'sectionsWithoutEvidence': r.sectionsWithoutEvidence,
          },
      ],
    });
  }
}
