import '../mbti_model.dart';

final part1Questions = [
  /// ===== E / I (20 ข้อ) =====
  MbtiQuestion(id: "mbti_p1_q1", textKey: "mbti_p1_q1", dimension: {"E": 1}),
  MbtiQuestion(id: "mbti_p1_q2", textKey: "mbti_p1_q2", dimension: {"I": 1}),
  MbtiQuestion(id: "mbti_p1_q3", textKey: "mbti_p1_q3", dimension: {"E": 1}),
  MbtiQuestion(id: "mbti_p1_q4", textKey: "mbti_p1_q4", dimension: {"I": 1}),
  MbtiQuestion(id: "mbti_p1_q5", textKey: "mbti_p1_q5", dimension: {"E": 1}),
  MbtiQuestion(id: "mbti_p1_q6", textKey: "mbti_p1_q6", dimension: {"I": 1}),
  MbtiQuestion(id: "mbti_p1_q7", textKey: "mbti_p1_q7", dimension: {"E": 1}),
  MbtiQuestion(id: "mbti_p1_q8", textKey: "mbti_p1_q8", dimension: {"I": 1}),
  MbtiQuestion(id: "mbti_p1_q9", textKey: "mbti_p1_q9", dimension: {"E": 1}),
  MbtiQuestion(id: "mbti_p1_q10", textKey: "mbti_p1_q10", dimension: {"I": 1}),
  MbtiQuestion(id: "mbti_p1_q11", textKey: "mbti_p1_q11", dimension: {"E": 1}),
  MbtiQuestion(id: "mbti_p1_q12", textKey: "mbti_p1_q12", dimension: {"I": 1}),
  MbtiQuestion(id: "mbti_p1_q13", textKey: "mbti_p1_q13", dimension: {"E": 1}),
  MbtiQuestion(id: "mbti_p1_q14", textKey: "mbti_p1_q14", dimension: {"I": 1}),
  MbtiQuestion(id: "mbti_p1_q15", textKey: "mbti_p1_q15", dimension: {"E": 1}),
  MbtiQuestion(id: "mbti_p1_q16", textKey: "mbti_p1_q16", dimension: {"I": 1}),
  MbtiQuestion(id: "mbti_p1_q17", textKey: "mbti_p1_q17", dimension: {"E": 1}),
  MbtiQuestion(id: "mbti_p1_q18", textKey: "mbti_p1_q18", dimension: {"I": 1}),
  MbtiQuestion(id: "mbti_p1_q19", textKey: "mbti_p1_q19", dimension: {"E": 1}),
  MbtiQuestion(id: "mbti_p1_q20", textKey: "mbti_p1_q20", dimension: {"I": 1}),

  /// ===== S / N (20 ข้อ) =====
  MbtiQuestion(id: "mbti_p1_q21", textKey: "mbti_p1_q21", dimension: {"S": 1}),
  MbtiQuestion(id: "mbti_p1_q22", textKey: "mbti_p1_q22", dimension: {"N": 1}),
  MbtiQuestion(id: "mbti_p1_q23", textKey: "mbti_p1_q23", dimension: {"S": 1}),
  MbtiQuestion(id: "mbti_p1_q24", textKey: "mbti_p1_q24", dimension: {"N": 1}),
  MbtiQuestion(id: "mbti_p1_q25", textKey: "mbti_p1_q25", dimension: {"S": 1}),
  MbtiQuestion(id: "mbti_p1_q26", textKey: "mbti_p1_q26", dimension: {"N": 1}),
  MbtiQuestion(id: "mbti_p1_q27", textKey: "mbti_p1_q27", dimension: {"S": 1}),
  MbtiQuestion(id: "mbti_p1_q28", textKey: "mbti_p1_q28", dimension: {"N": 1}),
  MbtiQuestion(id: "mbti_p1_q29", textKey: "mbti_p1_q29", dimension: {"S": 1}),
  MbtiQuestion(id: "mbti_p1_q30", textKey: "mbti_p1_q30", dimension: {"N": 1}),
  MbtiQuestion(id: "mbti_p1_q31", textKey: "mbti_p1_q31", dimension: {"S": 1}),
  MbtiQuestion(id: "mbti_p1_q32", textKey: "mbti_p1_q32", dimension: {"N": 1}),
  MbtiQuestion(id: "mbti_p1_q33", textKey: "mbti_p1_q33", dimension: {"S": 1}),
  MbtiQuestion(id: "mbti_p1_q34", textKey: "mbti_p1_q34", dimension: {"N": 1}),
  MbtiQuestion(id: "mbti_p1_q35", textKey: "mbti_p1_q35", dimension: {"S": 1}),
  MbtiQuestion(id: "mbti_p1_q36", textKey: "mbti_p1_q36", dimension: {"N": 1}),
  MbtiQuestion(id: "mbti_p1_q37", textKey: "mbti_p1_q37", dimension: {"S": 1}),
  MbtiQuestion(id: "mbti_p1_q38", textKey: "mbti_p1_q38", dimension: {"N": 1}),
  MbtiQuestion(id: "mbti_p1_q39", textKey: "mbti_p1_q39", dimension: {"S": 1}),
  MbtiQuestion(id: "mbti_p1_q40", textKey: "mbti_p1_q40", dimension: {"N": 1}),
];
