// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKHuN35ud0E3f_CcnupFjqjr4j9RCVTrQ',
    appId: '1:239840538753:web:5edbf627980612ae9c9d80',
    messagingSenderId: '239840538753',
    projectId: 'knowme-app-694e1',
    authDomain: 'knowme-app-694e1.firebaseapp.com',
    storageBucket: 'knowme-app-694e1.firebasestorage.app',
    measurementId: 'G-Z5LPZEGQFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0-EUV5b9IiSSTeI06gU93we7E_UBYAeA',
    appId: '1:239840538753:android:f017669821e0e8f09c9d80',
    messagingSenderId: '239840538753',
    projectId: 'knowme-app-694e1',
    storageBucket: 'knowme-app-694e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAqQXTnxMZbFFNQ4srvlBRg45GsZgNq7I',
    appId: '1:239840538753:ios:ac19b1bebcd2b3589c9d80',
    messagingSenderId: '239840538753',
    projectId: 'knowme-app-694e1',
    storageBucket: 'knowme-app-694e1.firebasestorage.app',
    androidClientId: '239840538753-soahjmliurefpqev2h8bnjss65mbe3cp.apps.googleusercontent.com',
    iosClientId: '239840538753-jolebolnl1mtbidaddpnqqqih6g7hj49.apps.googleusercontent.com',
    iosBundleId: 'com.example.knowme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAqQXTnxMZbFFNQ4srvlBRg45GsZgNq7I',
    appId: '1:239840538753:ios:ac19b1bebcd2b3589c9d80',
    messagingSenderId: '239840538753',
    projectId: 'knowme-app-694e1',
    storageBucket: 'knowme-app-694e1.firebasestorage.app',
    androidClientId: '239840538753-soahjmliurefpqev2h8bnjss65mbe3cp.apps.googleusercontent.com',
    iosClientId: '239840538753-jolebolnl1mtbidaddpnqqqih6g7hj49.apps.googleusercontent.com',
    iosBundleId: 'com.example.knowme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKHuN35ud0E3f_CcnupFjqjr4j9RCVTrQ',
    appId: '1:239840538753:web:ea668305db574b289c9d80',
    messagingSenderId: '239840538753',
    projectId: 'knowme-app-694e1',
    authDomain: 'knowme-app-694e1.firebaseapp.com',
    storageBucket: 'knowme-app-694e1.firebasestorage.app',
    measurementId: 'G-1ED1ZE0758',
  );
}
