#!/usr/bin/env python3
"""Emit production test units + foundation JSON chunk for Batch 8."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "tool" / "output" / "batch8_planet_library.json"
TEST_OUT = ROOT / "test/validation/thai/generated/batch8_planet_library_units.dart"
JSON_OUT = ROOT / "tool/output/batch8_foundation_units.json"


def dart_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def main() -> None:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    units = data["units"]
    entities = {e["id"]: e for e in data["entities"]}

    test_lines = [
        "// Generated by tool/emit_batch8_production.dart — do not hand-edit.",
        "import 'package:knowme/features/astrology/thai/knowledge/canon/atomic/atomic_knowledge_unit.dart';",
        "import 'package:knowme/features/astrology/thai/knowledge/canon/atomic/atomic_relation.dart';",
        "import 'package:knowme/features/astrology/thai/knowledge/canon/canonical_knowledge_node.dart'",
        "    show KnowledgeConfidence;",
        "",
        "List<AtomicKnowledgeUnit> batch8PlanetLibraryUnits({",
        "  required AtomicKnowledgeUnit Function({",
        "    required String id,",
        "    required String subject,",
        "    required AtomicRelation relation,",
        "    required String object,",
        "    AtomicEntityKind objectKind,",
        "    required String page,",
        "  }) unit,",
        "}) => [",
    ]
    json_units = []
    for u in units:
        test_lines.append("  unit(")
        test_lines.append(f"    id: {dart_str(u['id'])},")
        test_lines.append(f"    subject: {dart_str(u['subject'])},")
        test_lines.append(f"    relation: AtomicRelation.relatesTo,")
        test_lines.append(f"    object: {dart_str(u['object'])},")
        test_lines.append("    objectKind: AtomicEntityKind.keyword,")
        test_lines.append(f"    page: {dart_str(u['page'])},")
        test_lines.append("  ),")
        json_units.append(
            {
                "id": u["id"],
                "subject": u["subject"],
                "subjectKind": "planet",
                "relation": "relates_to",
                "object": u["object"],
                "objectKind": "keyword",
                "domain": "planetLibrary",
                "strength": "none",
                "confidence": "high",
                "evidence": {"bookId": "mahabhut", "page": u["page"]},
            }
        )
    test_lines.extend(["];", ""])

    TEST_OUT.parent.mkdir(parents=True, exist_ok=True)
    TEST_OUT.write_text("\n".join(test_lines), encoding="utf-8")
    JSON_OUT.write_text(json.dumps(json_units, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {len(units)} test units -> {TEST_OUT}")
    print(f"Wrote {len(json_units)} JSON units -> {JSON_OUT}")


if __name__ == "__main__":
    main()
