#!/usr/bin/env python3
"""Emit Dart attribute value entities from batch8_planet_library.json."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "tool" / "output" / "batch8_planet_library.json"
OUT = (
    ROOT
    / "lib/features/astrology/thai/knowledge/canon/ontology/canon_ontology_attribute_values.dart"
)


def dart_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def main() -> None:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    entities = data["entities"]
    lines = [
        "/// Canon Ontology V3 — Planet Library attribute value tokens (D-072).",
        "///",
        "/// Controlled vocabulary only: stable ids + verbatim Thai surface forms",
        "/// from `หลักมหาภูต` pp.30–36. Each value's [parentId] is an",
        "/// [attributeCategory]. No meanings or planet relationships encoded here.",
        "///",
        "/// Generated by tool/generate_batch8_planet_library.py — do not hand-edit.",
        "library;",
        "",
        "import 'package:knowme/features/astrology/thai/knowledge/canon/ontology/canonical_entity.dart';",
        "import 'package:knowme/features/astrology/thai/knowledge/canon/ontology/ontology_category.dart';",
        "",
        "abstract final class CanonOntologyAttributeValues {",
        "  static const List<CanonicalEntity> all = [",
    ]
    for e in entities:
        thai = e["thai"]
        slug = e["id"].split(".", 2)[2]
        roman = slug.replace("_", " ").title()
        lines.append("    CanonicalEntity(")
        lines.append(f"      id: {dart_str(e['id'])},")
        lines.append(f"      canonicalName: {dart_str(roman)},")
        lines.append("      category: OntologyCategory.attribute,")
        lines.append(f"      parentId: {dart_str(e['parentId'])},")
        lines.append(f"      aliases: [{dart_str(thai)}],")
        lines.append("    ),")
    lines.extend(
        [
            "  ];",
            "}",
            "",
        ]
    )
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(entities)} entities -> {OUT}")


if __name__ == "__main__":
    main()
